config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy' 
  end
  root "users#index"
      resources :users, only: [:index, :show] do
        resources :posts, only: [:index, :show, :new, :create, :edit, :update, :destroy] do 
          resources :comments, only: [:new, :create, :edit, :update, :destroy]
          resources :likes, only: [:create]
        end              
    end
    
    namespace :api do
      namespace :v1 do
        post "/sign_in", to: 'users#sign_in'
        resources :users, only: [:index] do        
          resources :posts, only: [:index, :show] do
            resources :comments, only: [:index, :create]
          end
        end
      end
    end

  end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'user_id'
  has_many :comments, foreign_key: 'user_id'
  has_many :likes, foreign_key: 'user_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def most_recent_posts
    posts.limit(3).order(created_at: :desc)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  def index
    @users = User.all

    render json: {
      user: @users
    }
  end

  def sign_in
    @user = User.find_by(email: user_params[email])

    if @user&.authenticate(user_params[:password])
      token = encode_token({ user_id: @user.id })
      render json: { user: @user, token: }, status: :ok
    else
      render json: { error: 'Invalid email or password' }, status: :unprocessable_entity
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user_posts = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1>Here is a list of all users</h1>
<% if user_signed_in?%>
 <div><%= button_to link_to 'Sign Out', destroy_user_session_path, method: :delete %></div>
 <% else %>
<%= render 'layouts/devise_flash' %> 
 <% end %>
 
<div class='all-users'>
<% @users.each do |user| %>
  <section class='user-details' style='border: 1px solid black;'>
    <div class='photo'>    
      <img src='<%=user.photo%>' alt='photo' style='width:12px;height:12px;'/>
    </div>

    <div>
      <h2><%= link_to user.name, user_path(user) %> </h2>  
      <span> Number of posts:<%= user.posts_counter || 0 %> </span>
    </div>

  </section>
  <br>
<% end %>
</div>

app/views/users/show.html.erb
<h1>Here is for a given user</h1>
<% if user_signed_in?%>
 <div><%= button_to link_to 'Sign Out', destroy_user_session_path, method: :delete %></div> 
 <% else %>
<%= render 'layouts/devise_flash' %> 
 <% end %>

<h3><%= link_to 'Create New Post', new_user_post_path(@user_posts) %>  </h3>

<%= link_to "Back", users_path %>

<div class='user-posts'>

<div class='bio-card'  style='border: 1px solid black;'>

  <div class='photo'>
    <img src='<%= @user_posts.photo %>' alt='photo' />
  </div>

  <div class='bio-details'>
    <h2> <%= @user_posts.name %> </h2>
    <h3> Bio: <%= @user_posts.bio %> </h3>
    <span>Number of posts: <%= @user_posts.posts_counter || 0 %>  </span>
    </div>

</div>
<br>

<% @user_posts.most_recent_posts.each_with_index do |post, index| %>  
  <div class='post-details' style='border: 1px solid black;'>
    <span>Post:<%= index+1 %> </span>
    <h4> Title: <%= link_to post.title, user_post_path(post.user_id, post.id ) %> </h4>
    <p> 
    <%=post.text%> 
     <% if can? :update, post%>
    <%= link_to "Edit Post", edit_user_post_path(post.user_id, post.id)%> 
    <% end %>
    </p>
    

    <span> Comments: <%= post.comments_counter || 0 %> Likes:<%=post.likes_counter || 0 %> </span> 
   
    
  </div>

<% end %>

<%= link_to user_posts_path(@user_posts) do%>
  <button> See all posts </button>
<% end %>

</div>