config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy' 
  end
  root "users#index"
      resources :users, only: [:index, :show] do
        resources :posts, only: [:index, :show, :new, :create, :edit, :update, :destroy] do 
          resources :comments, only: [:new, :create, :edit, :update, :destroy]
          resources :likes, only: [:create]
        end              
    end
    
    namespace :api do
      namespace :v1 do
        post "/sign_in", to: 'users#sign_in'
        resources :users, only: [:index] do        
          resources :posts, only: [:index, :show] do
            resources :comments, only: [:index, :create]
          end
        end
      end
    end

  end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, class_name: 'User'
  has_many :comments, foreign_key: 'post_id', dependent: :destroy
  has_many :likes, foreign_key: 'post_id', dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_create :update_posts_counter

  def update_posts_counter
    user.increment!(:posts_counter)
  end

  def most_recent_comments(id)
    comments.includes(:user).where(post_id: id).limit(5).order(created_at: :desc)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @post = @user.posts

    render json: @post
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @post = @user.posts
  end

  def new
    @post = Post.new

    respond_to do |format|
      format.html { render :new, locals: { post: @post } }
    end
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.comments_counter = 0
    @post.likes_counter = 0

    respond_to do |format|
      format.html do
        if @post.save
          flash[:success] = 'Post created successfully'
          redirect_to user_path(current_user)
        else
          flash.now[:error] = 'Error: Post could not be saved'
          redirect_to new_user_post_path(current_user)
        end
      end
    end
  end

  def show
    @post = Post.where('id = ?', params[:id])
    @comments = Comment.includes(:user).where('post_id = ?', params[:id])
    authorize! :read, @post
    authorize! :read, @comments
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    authorize! :update, @post
    if @post.update(post_params)
      flash[:success] = 'Post was successfully updated'
      redirect_to user_path(@post.user_id)
    else
      flash[:error] = 'Something went wrong'
      render 'edit'
    end
  end

  def destroy
    @post = Post.includes(:user).find(params[:id])
    @post.user.decrement!(:posts_counter)
    authorize! :destroy, @post
    if @post.destroy
      flash[:success] = 'Post was successfully deleted.'
    else
      flash[:error] = 'Something went wrong'
    end
    redirect_to user_path(@post.user_id)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/posts/_form.html.erb
<%= form_with model: @post, url: user_posts_path, method: :post, local: true do |f|%>
<div class="form-card">
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :text %>
    <%= f.text_area :text %>
  </div>

  <div>
    <%= f.submit "Create New Post" %>
  </div>
  </div>

<% end %>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>
<%= form_with model: @post, url: user_post_path, method: :put, local: true do |f|%>
<div class="form-card">
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :text %>
    <%= f.text_area :text %>
  </div>

  <div>
    <%= f.submit %>
  </div>
  </div>

<% end %>

app/views/posts/index.html.erb
<h1>Here is a list of all posts for a given user</h1>

<% if user_signed_in?%>
 <div><%= button_to link_to 'Sign Out', destroy_user_session_path, method: :delete %></div>
 <% else %>
<%= render 'layouts/devise_flash' %> 
 <% end %>
 
<h3><%= link_to 'Create New Post', new_user_post_path(@user) %>  </h3>

<%= link_to "Back", user_path(@user) %>

<div>

  <div class="bio-card" style='border: 1px solid black;'>
    <img src='<%= @user.photo %>' alt='photo'/>
    <div class='bio-details'>
      <h2>Name: <%= @user.name %> </h2>
      <span>Number of post:  <%= @user.posts_counter || 0 %> </span>
    </div>
  </div>

  <div class='post-details'>
    <% @post.each_with_index do |post, index| %>
      <div style='border: 1px solid black;'>
        <span>Post:<%= index+1 %> </span>
        <h3>Title: <%= link_to post.title, user_post_path(@user, post) %> </h3>
        <p> <%= post.text %> </p>
        
        <span> Comments: <%= post.comments_counter || 0 %>  Likes: <%= post.likes_counter || 0 %> </span>
      </div>

      <div style='border: 1px solid black;'> 

        <%post.most_recent_comments(post.id).each do | commenter |%> 
          <p> 
          <strong><%=commenter.user.name%> </strong>: <%= commenter.text %> 
          <% if can? :update, commenter%>
          <%= link_to "Edit", edit_user_post_comment_path(post.user_id, post.id, commenter.id)%> 
          <% end %>
          </p>  
                    
        <% end %>

        <span><%= link_to 'Add new comment', new_user_post_comment_path(post.user_id,post.id) %>  </span>

        <%= form_with url: "/users/#{post.user_id}/posts/#{post.id}/likes", method: :post, local: true do |f|%>
          <div class="form-card">     
            <div>
              <%= f.submit "Like" %>
            </div>
          </div>  
        <% end %>

      </div>
      <br>
      
    <% end %>

    
  </div>
     <button id='pagination' >Pagination</button>
</div>

app/views/posts/new.html.erb
<h1> Create New Post </h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<h1>Here is a list of all posts for a given user and for a given post</h1>

<% if user_signed_in?%>
 <div><%= button_to link_to 'Sign Out', destroy_user_session_path, method: :delete %></div>
 <% else %>
<%= render 'layouts/devise_flash' %> 
 <% end %>
 
<h3><%= link_to 'Create New Post', new_user_post_path(@post[0].user_id) %>  </h3>

<%= link_to "Back", user_posts_path(@post[0].user_id) %>

<div>

<% @post.each do | post | %>
  
  <div style='border: 1px solid black;'>
    <h4>Post by <%= post.user.name %> </h4>
    <span> Comments: <%= post.comments_counter || 0 %>  Likes: <%= post.likes_counter || 0 %> </span>
    <h3>Title: <%= post.title %> </h3>
    <p> <%= post.text %> </p>
    <% if can? :destroy, @post%>
    <%= button_to "Delete Post", "/users/#{post.user_id}/posts/#{post.id}", method: :delete, data: {confirm: "Are you sure you wantto delete post"}%>
    <% end %>
  </div>
<% end %>
</div>
<div style='border: 1px solid black;'>
<% @comments.each do |commenter| %>
  <p> 
    <strong>
      <%= commenter.user.name %>:
    </strong> <%= commenter.text %>

    <% if can? :update, commenter %>
    <%= link_to "Edit", edit_user_post_comment_path(commenter.user_id, commenter.post_id, commenter.id)%>
    <% end %>

    <% if can? :destroy, commenter %>
    <%= button_to "Delete Comment", "/users/#{commenter.user_id}/posts/#{commenter.post_id}/comments/#{commenter.id}", method: :delete, data: {confirm: "Are you sure you wantto delete post"}%>
    <% end %>
  </p>
  
<% end %>
<h3><%= link_to 'Add new comment', new_user_post_comment_path(@post[0].user_id,@post[0].id) %>  </h3>
<%= render "likes/form" %>
</div>

</div>